// sites/angular/src/app/home.ts
import { Component } from '@angular/core';
import { NgOptimizedImage } from '@angular/common';

@Component({
  selector: 'app-home',
  imports: [NgOptimizedImage],
  template: `
    <h1>Angular on Bunny Storage</h1>
    <p>With Bunny Optimizer on, each width in this image's srcset is resized at the edge.</p>
    <img ngSrc="/images/hero.png" width="1737" height="893" sizes="100vw" priority alt="A bunny watching a machine turn HTML into Markdown" />
  `,
})
export class Home {}

// sites/react-router/app/routes/home.tsx
import { Link } from "react-router";
import type { Route } from "./+types/home";
import { BunnyImage } from "../components/BunnyImage";

export function meta({}: Route.MetaArgs) {
  return [{ title: "React Router on Bunny Storage" }];
}

export default function Home() {
  return (
    <main>
      <h1>React Router on Bunny Storage</h1>
      <p>A single-page app built with server rendering turned off.</p>
      <Link to="/about">About</Link>
      <BunnyImage src="/images/hero.png" alt="A bunny watching a machine turn HTML into Markdown" width={1737} height={893} />
    </main>
  );
}
