// stream/player-nextjs/components/demo-player.tsx
"use client";

import { useState } from "react";
import type { Player, TimeUpdate } from "player.js";
import { BunnyPlayer } from "@/components/bunny-player";

const rates = [1, 1.5, 2];

function formatTime(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const rest = Math.floor(seconds % 60);

  return `${minutes}:${String(rest).padStart(2, "0")}`;
}

export function DemoPlayer({ libraryId, videoId }: { libraryId: string; videoId: string }) {
  const [player, setPlayer] = useState<Player | null>(null);
  const [playing, setPlaying] = useState(false);
  const [muted, setMuted] = useState(false);
  const [rate, setRate] = useState(1);
  const [time, setTime] = useState<TimeUpdate>({ seconds: 0, duration: 0 });
  const [log, setLog] = useState<string[]>([]);

  const record = (event: string) =>
    setLog((entries) => [`${new Date().toLocaleTimeString()}  ${event}`, ...entries].slice(0, 5));

  const toggleMute = () => {
    if (!player) return;

    // Ask the player first, because viewers can also mute from its own controls.
    player.getMuted((isMuted) => {
      if (isMuted) player.unmute();
      else player.mute();
      setMuted(!isMuted);
    });
  };

  const changeRate = (value: number) => {
    // npm player.js 0.1.0 has no setPlaybackRate(), so send the raw command.
    player?.send({ method: "setPlaybackRate", value });
    setRate(value);
  };

  return (
    <>

      <BunnyPlayer
        libraryId={libraryId}
        videoId={videoId}
        params={{ preload: true }}
        onReady={(instance) => {
          setPlayer(instance);
          // Library settings can autoplay or start muted, so read the real state.
          instance.getPaused((paused) => setPlaying(!paused));
          instance.getMuted(setMuted);
          instance.on("playbackratechange", setRate);
          record("ready");
        }}
        onPlay={() => {
          setPlaying(true);
          record("play");
        }}
        onPause={() => {
          setPlaying(false);
          record("pause");
        }}
        onEnded={() => {
          setPlaying(false);
          record("ended");
        }}
        onTimeUpdate={setTime}
      />

      <progress max={time.duration || 1} value={time.seconds} />

      <div className="controls">
        <button
          type="button"
          disabled={!player}
          onClick={() => (playing ? player?.pause() : player?.play())}
        >
          {playing ? "Pause" : "Play"}
        </button>
        <button type="button" disabled={!player} onClick={() => player?.setCurrentTime(0)}>
          Restart
        </button>
        <button type="button" disabled={!player} onClick={toggleMute}>
          {muted ? "Unmute" : "Mute"}
        </button>
        {rates.map((value) => (
          <button
            key={value}
            type="button"
            disabled={!player}
            aria-pressed={rate === value}
            onClick={() => changeRate(value)}
          >
            {value}x
          </button>
        ))}
        <span className="time">
          {formatTime(time.seconds)} / {formatTime(time.duration)}
        </span>
      </div>

      <ol className="log" aria-label="Player events">
        {log.length === 0 ? <li>Waiting for the player…</li> : null}
        {log.map((entry, index) => (
          <li key={index}>{entry}</li>
        ))}
      </ol>
    </>
  );
}

// stream/player-vue/src/components/DemoPlayer.vue
<script setup lang="ts">
import { ref, shallowRef } from "vue";
import type { Player, TimeUpdate } from "player.js";
import BunnyPlayer from "./BunnyPlayer.vue";

defineProps<{ libraryId: string; videoId: string }>();

const rates = [1, 1.5, 2];

const player = shallowRef<Player | null>(null);
const playing = ref(false);
const muted = ref(false);
const rate = ref(1);
const time = ref<TimeUpdate>({ seconds: 0, duration: 0 });
const log = ref<string[]>([]);

function formatTime(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const rest = Math.floor(seconds % 60);

  return `${minutes}:${String(rest).padStart(2, "0")}`;
}

function record(event: string) {
  log.value = [`${new Date().toLocaleTimeString()}  ${event}`, ...log.value].slice(0, 5);
}

function onReady(instance: Player) {
  player.value = instance;
  // Library settings can autoplay or start muted, so read the real state.
  instance.getPaused((paused) => (playing.value = !paused));
  instance.getMuted((isMuted) => (muted.value = isMuted));
  instance.on("playbackratechange", (value) => (rate.value = value));
  record("ready");
}

function onPlay() {
  playing.value = true;
  record("play");
}

function onPause() {
  playing.value = false;
  record("pause");
}

function onEnded() {
  playing.value = false;
  record("ended");
}

function togglePlay() {
  if (playing.value) player.value?.pause();
  else player.value?.play();
}

function toggleMute() {
  const instance = player.value;
  if (!instance) return;

  // Ask the player first, because viewers can also mute from its own controls.
  instance.getMuted((isMuted) => {
    if (isMuted) instance.unmute();
    else instance.mute();
    muted.value = !isMuted;
  });
}

function changeRate(value: number) {
  // npm player.js 0.1.0 has no setPlaybackRate(), so send the raw command.
  player.value?.send({ method: "setPlaybackRate", value });
  rate.value = value;
}
</script>

<template>
  <BunnyPlayer
    :library-id="libraryId"
    :video-id="videoId"
    :params="{ preload: true }"
    @ready="onReady"
    @play="onPlay"
    @pause="onPause"
    @ended="onEnded"
    @timeupdate="time = $event"
  />

  <progress :max="time.duration || 1" :value="time.seconds" />

  <div class="controls">
    <button type="button" :disabled="!player" @click="togglePlay">
      {{ playing ? "Pause" : "Play" }}
    </button>
    <button type="button" :disabled="!player" @click="player?.setCurrentTime(0)">Restart</button>
    <button type="button" :disabled="!player" @click="toggleMute">
      {{ muted ? "Unmute" : "Mute" }}
    </button>
    <button
      v-for="value in rates"
      :key="value"
      type="button"
      :disabled="!player"
      :aria-pressed="rate === value"
      @click="changeRate(value)"
    >
      {{ value }}x
    </button>
    <span class="time">{{ formatTime(time.seconds) }} / {{ formatTime(time.duration) }}</span>
  </div>

  <ol class="log" aria-label="Player events">
    <li v-if="log.length === 0">Waiting for the player…</li>
    <li v-for="(entry, index) in log" :key="index">{{ entry }}</li>
  </ol>
</template>
