// sites/react-router/app/components/BunnyImage.tsx
import type { ComponentProps } from "react";

// Set VITE_BUNNY_OPTIMIZER=true at build time to resize images at the edge with Bunny Optimizer.
const optimizer = import.meta.env.VITE_BUNNY_OPTIMIZER === "true";
const widths = [640, 960, 1280, 1920];

const optimized = (src: string, width: number) => `${src}?width=${width}&quality=75`;

type Props = ComponentProps<"img"> & { src: string; width: number; height: number };

export function BunnyImage({ src, sizes = "100vw", ...props }: Props) {
  if (!optimizer) return <img src={src} {...props} />;

  return (
    <img
      src={optimized(src, 1280)}
      srcSet={widths.map((w) => `${optimized(src, w)} ${w}w`).join(", ")}
      sizes={sizes}
      {...props}
    />
  );
}

// sites/vitepress/docs/.vitepress/components/BunnyImage.vue
<script lang="ts">
// Build with VITE_BUNNY_OPTIMIZER=true to let Bunny Optimizer resize images at the edge.
const enabled = import.meta.env.VITE_BUNNY_OPTIMIZER === 'true'
const widths = [640, 960, 1280, 1920]
const url = (src: string, width: number) => `${src}?width=${width}&quality=75`
</script>

<script setup lang="ts">
const { src, sizes = '100vw' } = defineProps<{ src: string; sizes?: string }>()
</script>

<template>
  <img
    v-if="enabled"
    :src="url(src, 1280)"
    :srcset="widths.map((w) => `${url(src, w)} ${w}w`).join(', ')"
    :sizes="sizes"
  />
  <img v-else :src="src" />
</template>
