// stream/upload-tus-sveltekit/src/lib/components/UploadedVideo.svelte
<script lang="ts">
	import { hasFailed, VideoStatusCode, type VideoStatus } from "$lib/bunny-stream";

	let { videoId, title }: { videoId: string; title: string } = $props();

	let video: VideoStatus | null = $state(null);
	let error: string | null = $state(null);

	// Poll until Bunny Stream finishes encoding or gives up.
	$effect(() => {
		let timer: ReturnType<typeof setTimeout>;
		let active = true;

		const poll = async () => {
			let response: Response;
			let body;
			try {
				response = await fetch(`/api/videos/${videoId}`);
				body = await response.json();
			} catch {
				// A dropped connection or a non-JSON error page.
				if (active) error = "Could not reach the server to check the video";
				return;
			}
			if (!active) return;
			if (!response.ok) {
				error = body.error ?? "Could not read the video status";
				return;
			}

			video = body;
			if (body.status !== VideoStatusCode.Finished && !hasFailed(body.status)) {
				timer = setTimeout(poll, 3000);
			}
		};

		poll();

		return () => {
			active = false;
			clearTimeout(timer);
		};
	});
</script>

{#if error}
	<p class="error">{error}</p>
{:else if !video}
	<p>Checking the video…</p>
{:else if hasFailed(video.status)}
	<p class="error">Bunny Stream could not encode {title}.</p>
{:else if video.status !== VideoStatusCode.Finished}
	<p>Encoding {title}… {video.encodeProgress}%</p>
{:else}
	<iframe
		src={video.embedUrl}
		{title}
		class="player"
		allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
		allowfullscreen
	></iframe>
{/if}

// stream/upload-tus-nuxt/app/components/UploadedVideo.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from "vue";
import { hasFailed, VideoStatusCode, type VideoStatus } from "#shared/bunny-stream";

const props = defineProps<{ videoId: string; title: string }>();

const video = ref<VideoStatus | null>(null);
const error = ref<string | null>(null);
let timer: ReturnType<typeof setTimeout> | undefined;
let active = true;

// Poll until Bunny Stream finishes encoding or gives up.
async function poll() {
  let response: Response;
  let body;
  try {
    response = await fetch(`/api/videos/${props.videoId}`);
    body = await response.json();
  } catch {
    // A dropped connection or a non-JSON error page.
    if (active) error.value = "Could not reach the server to check the video";
    return;
  }
  if (!active) return;
  if (!response.ok) {
    error.value = body.error ?? "Could not read the video status";
    return;
  }

  video.value = body;
  if (body.status !== VideoStatusCode.Finished && !hasFailed(body.status)) {
    timer = setTimeout(poll, 3000);
  }
}

onMounted(poll);
onBeforeUnmount(() => {
  active = false;
  clearTimeout(timer);
});
</script>

<template>
  <p v-if="error" class="error">{{ error }}</p>
  <p v-else-if="!video">Checking the video…</p>
  <p v-else-if="hasFailed(video.status)" class="error">Bunny Stream could not encode {{ title }}.</p>
  <p v-else-if="video.status !== VideoStatusCode.Finished">Encoding {{ title }}… {{ video.encodeProgress }}%</p>
  <iframe
    v-else
    :src="video.embedUrl"
    :title="title"
    class="player"
    allow="autoplay; encrypted-media; picture-in-picture; fullscreen"
    allowfullscreen
  />
</template>
